package viborita.enums;

public enum EstadoUsuarioEnum {

	/**
	 * Acciones
	 */
	LOGIN, LOGIN_OK, REGISTRO, NO_REGISTRADO, REGISTRO_OK, DATOS_INCORRECTOS, PW_MENOR_DE_CINCO_CHAR, USUARIO_EXISTENTE, USUARIO_INVALIDO, 
	OBTENER_SALAS, CREAR_SALA, CREACION_OK, SALA_EXISTENTE, DESCONECTAR_SALA, ELIMINAR_SALA, DESCONECTAR, TODO_OK;
	
}
