package viborita.enums;

public enum EstadoUsuarioEnum {

	/**
	 * Acciones
	 */
	LOGIN, LOGIN_OK, REGISTRO, NO_REGISTRADO, REGISTRO_OK, CAMPOS_VACIOS, DATOS_INCORRECTOS, PW_MENOR_DE_CINCO_CHAR, USUARIO_EXISTENTE, USUARIO_INVALIDO, LOBBY, CREAR_LOBBY, SNAKE_PING, UNIRSE_LOBBY, INICIAR_PARTIDA;
	
}
